# Generated by Django 5.0.3 on 2024-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер машины')),
                ('make', models.CharField(help_text='Фирма машины', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
