# Generated by Django 5.0.3 on 2024-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_create_model_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=51),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(help_text='Фирма Машины', max_length=50),
        ),
    ]
